
def getdata(title, author, page, year):
    data = []
    titles = ['Politics of Opportunism', 
              'Malayalam poetry', 
              'The Testaments',
              'Celestial Bodies',
              'Cheque book',
              'The Overstory',
              'The Braille edition',
              'Mind-Master',
              'Hemant Karkare',
              'Girl Power',
              'Braille Edition',
              'Bridgital Nation',
              'Fakir Hassen',
              'Turbulence',
              'Handbook',
              'Savarkar',
              'Glorious Diaspora',
              'First They Erased',
              'Obama: The Call of History',
              'Kashmirs untold',
              'Vivekadeepini',
              'Listening',
              'My Life, My Mission',
              'The Diary of Manu Gandhi',
              'A Prime Minister',
              'Lessons Life',
              'Indian Fiscal Federalism',
              'Chequered Brillance',
              'Designing Destiny',
              'Chosen'
              ]
    authors = ['Akkitham Achuthan',
               'Margaret Atwood',
               'Jokha Alharthi',
               'Vasdev Mohi',
               'Richard Powers',
               'PM Narendra Modi',
               'Hemant Karkares',
               'Chief Justice',
               'Karkares Daughter',
               'Prime Minister',
               'Shri N Chandrasekaran',
               'Neha J Hiranandani',
               'Roopa Pai',
               'Ministry of fisheries',
               'Vikram Sampath',
               'Indian Diaspora Club',
               'Habiburahman',
               'Peter Baker',
               'Satyarth Nayak',
               'Adi Shankaracharya',
               'Baba Ramdev',
               'Meenakshi Lekhi',
               'Tridip Suhrud',
               'Sushil Kumar',
               'Adi Shankaracharya',
               'Anupam Kher',
               'Ashis Ray',
               'Dr. Bibek Debroy',
               'Jairam Ramesh',
               'Kamlesh Patel'
               ]
    pages = ['57',
             '34',
             '345',
             '765',
             '23',
             '467',
             '45',
             '4567',
             '322',
             '57',
             '123',
             '678',
             '579',
             '833',
             '54',
             '3',
             '467',
             '689',
             '129',
             '569',
             '1234',
             '67',
             '457',
             '243',
             '345',
             '76',
             '457',
             '345',
             '78',
             '65',
             '46'
             ]
    years = ['1953',
             '1988',
             '1911',
             '1980',
             '1914',
             '1956',
             '1954',
             '1934',
             '1987',
             '1923',
             '1919',
             '1944',
             '1953',
             '1929',
             '1977',
             '1941',
             '1918',
             '1915',
             '1999',
             '1920',
             '1922',
             '1957',
             '1990',
             '1991',
             '1992',
             '1993',
             '1967',
             '1961',
             '1932',
             '1937',
             '1909'
             ]

    data.append(titles[title])
    data.append(authors[author])
    data.append(years[year])
    data.append(pages[page])
    data.append('initialization')

    return data